### ISSUE TITLE
Failed to finish nested step. Error: timeout of 30000ms exceeded. URL:... method: POST. Error starts randomly throwing in the middle of test execution.

### ISSUE THREAD

**Issue by toduyemi** [reportportal/agent-js-playwright#160]
**Describe the bug**
Hi in the middle of a test execution, sometimes i'll start getting non-playwright errors like this. I can't find anything in the documentation. Usually if a test times out, the terminal prints a playwright error, fails the test which makes it difficult to understand why i'm getting this weird report portal exception about timeouts. If I click the link(s), it tells me I'm not authorized to view page.

The test execution always starts of normally but somewhere in there reportportal starts to throw exceptions. There is no documentation on how to troubleshoot such an issue. The behaviour has been unpredictable to my eyes but definitely has increased in frequency in the last week or two. To the point, I can't get through a whole test execution. The only thing that's changed is an increase in the number of tests.

**Expected behavior**
For the terminal to only print line results from playwright.

**Screenshots**

https://github.com/user-attachments/assets/1d5f6577-2629-4285-922a-229f93a5a1d3

<img width="1100" alt="Screenshot 2024-11-06 at 12 34 35 PM" src="https://github.com/user-attachments/assets/74608a2b-bdce-4273-9a0a-99520296ac6b">

**Versions:**
 - OS, Browser - macOS Sonoma Google Chrome
"@playwright/test": "^1.47.2",
"@reportportal/agent-js-playwright": "^5.1.9",

**Comment by AmsterGet** [comment]
Hello @toduyemi !
I assume that timeout errors can be caused by uploading large files that are not within the acceptable size range defined by the ReportPortal server.
So, if you need to upload such files and there is no way to compress them, try increasing the allowable file size on the server side.
I'll share the link on how to do this a bit later.
I also suggest using the `api/v2` endpoint to report data via the ReportPortal Async API for better performance.

**Comment by AmsterGet** [comment]
You can change the file upload limits by providing env variables to [docker-compose](https://github.com/reportportal/reportportal/blob/master/docker-compose.yml#L222) for service api:
RP_UPLOAD_MAXUPLOADSIZE: 128MB
RP_UPLOAD_MAXFILESIZE: 64MB

**Comment by toduyemi** [comment]
@AmsterGet I tried the suggestion and I'm still getting this exception thrown. 
> I assume that timeout errors can be caused by uploading large files that are not within the acceptable size range defined by the ReportPortal server.
So, if you need to upload such files and there is no way to compress them, try increasing the allowable file size on the server side.
If files are being uploaded, they're files that RP uploads out-of-box. I haven't made any changes with regards to file uploads or test artifacts.
``` 
api:
    image: reportportal/service-api:5.12.1
    logging:
      <<: *logging
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      <<: *common-environment
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: info
      RP_REQUESTLOGGING: "false"
      AUDIT_LOGGER: "OFF"
      MANAGEMENT_HEALTH_ELASTICSEARCH_ENABLED: "false"
      RP_ENVIRONMENT_VARIABLE_ALLOW_DELETE_ACCOUNT: "false"
      JAVA_OPTS: >
        -Xmx1g 
        -XX:+HeapDumpOnOutOfMemoryError 
        -XX:HeapDumpPath=/tmp  
        -Dcom.sun.management.jmxremote.rmi.port=12349 
        -Dcom.sun.management.jmxremote 
        -Dcom.sun.management.jmxremote.local.only=false  
        -Dcom.sun.management.jmxremote.port=9010 
        -Dcom.sun.management.jmxremote.authenticate=false 
        -Dcom.sun.management.jmxremote.ssl=false 
        -Djava.rmi.server.hostname=0.0.0.0
      RP_JOBS_BASEURL: http://jobs:8686
      COM_TA_REPORTPORTAL_JOB_INTERRUPT_BROKEN_LAUNCHES_CRON: PT1H
      RP_ENVIRONMENT_VARIABLE_PATTERN-ANALYSIS_BATCH-SIZE: 100
      RP_ENVIRONMENT_VARIABLE_PATTERN-ANALYSIS_PREFETCH-COUNT: 1
      RP_ENVIRONMENT_VARIABLE_PATTERN-ANALYSIS_CONSUMERS-COUNT: 1
      COM_TA_REPORTPORTAL_JOB_LOAD_PLUGINS_CRON: PT10S
      COM_TA_REPORTPORTAL_JOB_CLEAN_OUTDATED_PLUGINS_CRON: PT10S
      REPORTING_QUEUES_COUNT: 10
      REPORTING_CONSUMER_PREFETCHCOUNT: 10
      REPORTING_PARKINGLOT_TTL_DAYS: 7
      RP_UPLOAD_MAXUPLOADSIZE: 128MB
      RP_UPLOAD_MAXFILESIZE: 64MB
    volumes:
      - storage:/data/storage
      ```
Did I put the env variables in the correct place?
